name: release

on:
  push:
    branches:
      - "main"
    tags:
      - "app-v*"

env:
  srcdir : "./todo-api/FusionDev.Samples.TodoApi"

jobs:
  build-and-release:  
    runs-on: windows-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v1

      - name: Ensure dotnet SDK installed
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: ${{ env.srcdir}}/global.json

      - name: Build applicaiton
        shell: pwsh
        working-directory: ${{ env.srcdir }}
        run: |
          dotnet restore
          dotnet build

      - name: Publish dotnet applicaiton
        shell: pwsh
        working-directory: ${{ env.srcdir }}
        run: |
          dotnet publish -o ../publish/default
          Compress-Archive -Path ../publish/default/* ../publish/default.zip

      - name: Publish dotnet applicaiton for Linux 
        shell: pwsh
        working-directory: ${{ env.srcdir }}
        run: |
          dotnet publish -o ../publish/linux-x64 --self-contained -r linux-x64 /p:PublishSingleFile=true
          cd ../publish/linux-x64
          tar -zcvf ../linux-x64.tar.gz *

      - name: Publish pipeline artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-artifacts
          path: ./todo-api/publish/

      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          prerelease: true
          files: |
            ./todo-api/publish/default.zip
            ./todo-api/publish/linux-x64.tar.gz
            ./todo-api/webdb.bicep
            ./todo-api/onprem.bicep


